/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.ControladorVistaMinimo;
import Recursos.fuentes.FontBSD;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 * Clase que muestra la interfaz del Minimo Comun Divisor
 * extiende de JFrame
 * @author Yonathan Alexander Martínez Padilla
 */
public class VistaMinimo extends javax.swing.JFrame {
    //Creamos una variable de tipo ControladorVistaMinimo que nos permita manejar
    //los eventos de los botones de la interfaz VistaMinimo
    ControladorVistaMinimo manejador = new ControladorVistaMinimo(this);

    /**
     * Creates new form VistaMinimo
     */
    public VistaMinimo() {
        initComponents();
        //Se centraliza la interfaz
        this.setLocationRelativeTo(null);
        //Se establece el estilo y tipo de fuente
        setFonts();
        //Invalidamos la edicion para el campo del resultado
        txt_resultadoMinimo.setEditable(false);
        //Agregamos el controlador a cada boton de nuestra interfaz
        btn_calcularMinimo.addActionListener(manejador);
        btn_ayudaMinimo.addActionListener(manejador);
        btn_limpiarMinimo.addActionListener(manejador);
        btn_regresarMinimo.addActionListener(manejador);
        //limpiamos los campos para prepararlos para el primer uso
        manejador.limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_tituloMinimo = new javax.swing.JLabel();
        lb_textoentreMinimo = new javax.swing.JLabel();
        txt_aMinimo = new javax.swing.JTextField();
        lb_yMinimo = new javax.swing.JLabel();
        txt_bMinimo = new javax.swing.JTextField();
        lb_utilizandoMinimo = new javax.swing.JLabel();
        btn_calcularMinimo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_resultadoMinimo = new javax.swing.JTextArea();
        btn_ayudaMinimo = new javax.swing.JButton();
        btn_limpiarMinimo = new javax.swing.JButton();
        btn_regresarMinimo = new javax.swing.JButton();
        lb_infoMinimo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));

        lb_tituloMinimo.setFont(new java.awt.Font("BSD I Believe In Love", 1, 48)); // NOI18N
        lb_tituloMinimo.setForeground(new java.awt.Color(240, 240, 240));
        lb_tituloMinimo.setText("Minimo Comun Divisor (M.C.D.)");

        lb_textoentreMinimo.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        lb_textoentreMinimo.setForeground(new java.awt.Color(240, 240, 240));
        lb_textoentreMinimo.setText("El minimo comun multiplo entre:");

        txt_aMinimo.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        txt_aMinimo.setText("###");

        lb_yMinimo.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        lb_yMinimo.setForeground(new java.awt.Color(240, 240, 240));
        lb_yMinimo.setText("y");

        txt_bMinimo.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        txt_bMinimo.setText("###");

        lb_utilizandoMinimo.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        lb_utilizandoMinimo.setForeground(new java.awt.Color(240, 240, 240));
        lb_utilizandoMinimo.setText("es utilizando el algoritmo de Euclides");

        btn_calcularMinimo.setBackground(new java.awt.Color(243, 156, 18));
        btn_calcularMinimo.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        btn_calcularMinimo.setForeground(new java.awt.Color(240, 240, 240));
        btn_calcularMinimo.setText("calcular");

        txt_resultadoMinimo.setColumns(20);
        txt_resultadoMinimo.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        txt_resultadoMinimo.setRows(5);
        jScrollPane1.setViewportView(txt_resultadoMinimo);

        btn_ayudaMinimo.setBackground(new java.awt.Color(243, 156, 18));
        btn_ayudaMinimo.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        btn_ayudaMinimo.setForeground(new java.awt.Color(240, 240, 240));
        btn_ayudaMinimo.setText("ayuda");

        btn_limpiarMinimo.setBackground(new java.awt.Color(243, 156, 18));
        btn_limpiarMinimo.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        btn_limpiarMinimo.setForeground(new java.awt.Color(240, 240, 240));
        btn_limpiarMinimo.setText("limpiar campos");

        btn_regresarMinimo.setBackground(new java.awt.Color(243, 156, 18));
        btn_regresarMinimo.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        btn_regresarMinimo.setForeground(new java.awt.Color(240, 240, 240));
        btn_regresarMinimo.setText("regresar");

        lb_infoMinimo.setFont(new java.awt.Font("BSD I Believe In Love", 1, 14)); // NOI18N
        lb_infoMinimo.setForeground(new java.awt.Color(240, 240, 240));
        lb_infoMinimo.setText("Info:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_tituloMinimo)
                .addGap(114, 114, 114))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(btn_calcularMinimo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lb_textoentreMinimo)
                                .addGap(18, 18, 18)
                                .addComponent(txt_aMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lb_yMinimo)
                                .addGap(18, 18, 18)
                                .addComponent(txt_bMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lb_utilizandoMinimo))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_infoMinimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_regresarMinimo)
                        .addGap(18, 18, 18)
                        .addComponent(btn_limpiarMinimo)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ayudaMinimo)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_tituloMinimo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_textoentreMinimo)
                    .addComponent(txt_aMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_yMinimo)
                    .addComponent(txt_bMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_utilizandoMinimo))
                .addGap(18, 18, 18)
                .addComponent(btn_calcularMinimo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ayudaMinimo)
                    .addComponent(btn_limpiarMinimo)
                    .addComponent(btn_regresarMinimo)
                    .addComponent(lb_infoMinimo))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMinimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMinimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMinimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMinimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMinimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ayudaMinimo;
    private javax.swing.JButton btn_calcularMinimo;
    private javax.swing.JButton btn_limpiarMinimo;
    private javax.swing.JButton btn_regresarMinimo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_infoMinimo;
    private javax.swing.JLabel lb_textoentreMinimo;
    private javax.swing.JLabel lb_tituloMinimo;
    private javax.swing.JLabel lb_utilizandoMinimo;
    private javax.swing.JLabel lb_yMinimo;
    private javax.swing.JTextField txt_aMinimo;
    private javax.swing.JTextField txt_bMinimo;
    private javax.swing.JTextArea txt_resultadoMinimo;
    // End of variables declaration//GEN-END:variables
    /**
     * Metodo que establece el tipo de fuente y estilo de los componentes de la
     * interfaz, esto independientemente del sistema operativo
     */
    private void setFonts() {
        FontBSD fonts = new FontBSD();
        lb_tituloMinimo.setFont(fonts.getMyFont(1, 48));
        lb_textoentreMinimo.setFont(fonts.getMyFont(1, 18));
        lb_yMinimo.setFont(fonts.getMyFont(1, 18));
        lb_utilizandoMinimo.setFont(fonts.getMyFont(1, 18));
        lb_infoMinimo.setFont(fonts.getMyFont(1, 14));
        txt_aMinimo.setFont(fonts.getMyFont(1, 18));
        txt_bMinimo.setFont(fonts.getMyFont(1, 18));
        txt_resultadoMinimo.setFont(fonts.getMyFont(1, 18));
        btn_calcularMinimo.setFont(fonts.getMyFont(1, 18));
        btn_regresarMinimo.setFont(fonts.getMyFont(1, 18));
        btn_limpiarMinimo.setFont(fonts.getMyFont(1, 18));
        btn_ayudaMinimo.setFont(fonts.getMyFont(1, 18));
    }
    /**
     * Metodo que devuelve la etiqueta de la informacion
     * @return un objeto de tipo JLabel con la etiqueta de la informacion
     */
    public JLabel getLb_infoMinimo() {
        return lb_infoMinimo;
    }
    
    /**
     * Metodo que devuelve el campo del valor a
     * @return un objeto de JTextField con el campo del valor a
     */
    public JTextField getTxt_aMinimo() {
        return txt_aMinimo;
    }
    
    /**
     * Metodo que devuelve el campo del valor b
     * @return un objeto de JTextField con el campo del valor b
     */
    public JTextField getTxt_bMinimo() {
        return txt_bMinimo;
    }
    
    /**
     * Metodo que devuelve el campo del valor resultado
     * @return un objeto de JTextField con el campo del valor resultado
     */
    public JTextArea getTxt_resultadoMinimo() {
        return txt_resultadoMinimo;
    }
}
