/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Recursos.fuentes.FontBSD;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Yonathan Alexander Martínez Padilla
 */
public class VistaAyudaExponenciacion extends javax.swing.JFrame {

    /**
     * Creates new form VistaAyudaExponenciacion
     */
    public VistaAyudaExponenciacion() {
        initComponents();
        //Centramos la interfaz
        this.setLocationRelativeTo(null);
        //garantizamos el estilo y tipo de fuente
        setFonts();
        //Agregamos el manejador del boton
        btn_cerrarVistaAyudaExponenciacion.addActionListener(new ControladorBotonesVistaAyudaExponenciacion(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_cerrarVistaAyudaExponenciacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(750, 446));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 446));

        jLabel1.setFont(new java.awt.Font("BSD I Believe In Love", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Ayuda");

        jLabel3.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("La exponenciacion modular permite resolver operaciones del tipo");

        jLabel4.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Metodo clasico: consiste en elevar primero a con el exponente");

        jLabel5.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("a exponente(b) mod c. Existen dos maneras de hacerlo:");

        jLabel6.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("b y posteriormente obtener su modulo. Esto implica mas tiempo");

        jLabel7.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("y mayor poder de computo. Para encontrar el resultado es");

        jLabel8.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("necesario hacer el doble de operaciones de lo que indica el");

        jLabel9.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("exponente.");

        jLabel10.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Metodo rapido: consiste en obtener el modulo de a cada vez que se");

        jLabel11.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("multiplica por si mismo, esto impide que a crezca de manera excesiva.");

        jLabel12.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Consume menos tiempo y menor poder de computo.");

        btn_cerrarVistaAyudaExponenciacion.setBackground(new java.awt.Color(243, 156, 18));
        btn_cerrarVistaAyudaExponenciacion.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        btn_cerrarVistaAyudaExponenciacion.setForeground(new java.awt.Color(240, 240, 240));
        btn_cerrarVistaAyudaExponenciacion.setText("cerrar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(52, 52, 52)
                                        .addComponent(btn_cerrarVistaAyudaExponenciacion))
                                    .addComponent(jLabel11)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cerrarVistaAyudaExponenciacion)
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAyudaExponenciacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAyudaExponenciacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAyudaExponenciacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAyudaExponenciacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAyudaExponenciacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrarVistaAyudaExponenciacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void setFonts() {
        FontBSD fonts = new FontBSD();
        jLabel1.setFont(fonts.getMyFont(1, 30));
        jLabel10.setFont(fonts.getMyFont(1, 18));
        jLabel11.setFont(fonts.getMyFont(1, 18));
        jLabel12.setFont(fonts.getMyFont(1, 18));
        jLabel3.setFont(fonts.getMyFont(1, 18));
        jLabel4.setFont(fonts.getMyFont(1, 18));
        jLabel5.setFont(fonts.getMyFont(1, 18));
        jLabel6.setFont(fonts.getMyFont(1, 18));
        jLabel7.setFont(fonts.getMyFont(1, 18));
        jLabel8.setFont(fonts.getMyFont(1, 18));
        jLabel9.setFont(fonts.getMyFont(1, 18));
        btn_cerrarVistaAyudaExponenciacion.setFont(fonts.getMyFont(1, 18));
    }
}
class ControladorBotonesVistaAyudaExponenciacion implements ActionListener{
    //Creamos una variable que haga referencia a la interfaz de la cual controlamos
    //sus eventos
    private VistaAyudaExponenciacion vistaAyudaExponenciacion;
    
    /**
     * COnstructor de la clase
     * @param vistaAyudaExponenciacion hace referncia a la interfaz de la cual 
     * controlamos sus botones
     */
    public ControladorBotonesVistaAyudaExponenciacion
        (VistaAyudaExponenciacion vistaAyudaExponenciacion){
        this.vistaAyudaExponenciacion = vistaAyudaExponenciacion;
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        //Obtenemos una instancia del boton del cual se genero el evento
        JButton botonTemporal = (JButton) ae.getSource();
        
        //Ahora identificamos desde que boton se hizo el clic y asignamos acciones
        if(botonTemporal.getText().equalsIgnoreCase("cerrar")){
            //cerramos la ventana de ayuda
            vistaAyudaExponenciacion.dispose();
        }
    }
    
}