/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Recursos.fuentes.FontBSD;

/**
 *
 * @author ALEX
 */
public class VistaCongruencia extends javax.swing.JFrame {

    /**
     * Creates new form VistaCongruencia
     */
    public VistaCongruencia() {
        initComponents();
        this.setLocationRelativeTo(null);
        setFonts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_tituloCongruencia = new javax.swing.JLabel();
        lb_aCongruencia = new javax.swing.JLabel();
        txt_aCongruencia = new javax.swing.JTextField();
        lb_bCongruencia = new javax.swing.JLabel();
        txt_bCongruencia = new javax.swing.JTextField();
        lb_esCongruencia = new javax.swing.JLabel();
        btn_calcularCongruencia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_solucionCongruencia = new javax.swing.JTextArea();
        lb_infoCongruencia = new javax.swing.JLabel();
        btn_ayudaCongruencia = new javax.swing.JButton();
        btn_limpiarCongruencia = new javax.swing.JButton();
        btn_regresarCongruencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));

        lb_tituloCongruencia.setFont(new java.awt.Font("BSD I Believe In Love", 1, 48)); // NOI18N
        lb_tituloCongruencia.setForeground(new java.awt.Color(240, 240, 240));
        lb_tituloCongruencia.setText("Congruencia");

        lb_aCongruencia.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        lb_aCongruencia.setForeground(new java.awt.Color(240, 240, 240));
        lb_aCongruencia.setText("La congruencia entre a: ");

        txt_aCongruencia.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        txt_aCongruencia.setText("###");

        lb_bCongruencia.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        lb_bCongruencia.setForeground(new java.awt.Color(240, 240, 240));
        lb_bCongruencia.setText("y entre b: ");

        txt_bCongruencia.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        txt_bCongruencia.setText("###");

        lb_esCongruencia.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        lb_esCongruencia.setForeground(new java.awt.Color(240, 240, 240));
        lb_esCongruencia.setText("es:");

        btn_calcularCongruencia.setBackground(new java.awt.Color(243, 156, 18));
        btn_calcularCongruencia.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        btn_calcularCongruencia.setForeground(new java.awt.Color(240, 240, 240));
        btn_calcularCongruencia.setText("calcular");

        txt_solucionCongruencia.setColumns(20);
        txt_solucionCongruencia.setRows(5);
        jScrollPane1.setViewportView(txt_solucionCongruencia);

        lb_infoCongruencia.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        lb_infoCongruencia.setForeground(new java.awt.Color(240, 240, 240));
        lb_infoCongruencia.setText("Info:");

        btn_ayudaCongruencia.setBackground(new java.awt.Color(243, 156, 18));
        btn_ayudaCongruencia.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        btn_ayudaCongruencia.setForeground(new java.awt.Color(240, 240, 240));
        btn_ayudaCongruencia.setText("ayuda");

        btn_limpiarCongruencia.setBackground(new java.awt.Color(243, 156, 18));
        btn_limpiarCongruencia.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        btn_limpiarCongruencia.setForeground(new java.awt.Color(240, 240, 240));
        btn_limpiarCongruencia.setText("limpiar campos");

        btn_regresarCongruencia.setBackground(new java.awt.Color(243, 156, 18));
        btn_regresarCongruencia.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        btn_regresarCongruencia.setForeground(new java.awt.Color(240, 240, 240));
        btn_regresarCongruencia.setText("regresar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(lb_tituloCongruencia))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(lb_aCongruencia)
                        .addGap(18, 18, 18)
                        .addComponent(txt_aCongruencia, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_bCongruencia)
                        .addGap(18, 18, 18)
                        .addComponent(txt_bCongruencia, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_esCongruencia))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(497, 497, 497)
                        .addComponent(btn_calcularCongruencia)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 167, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_infoCongruencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_regresarCongruencia)
                .addGap(18, 18, 18)
                .addComponent(btn_limpiarCongruencia)
                .addGap(18, 18, 18)
                .addComponent(btn_ayudaCongruencia)
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_tituloCongruencia)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_aCongruencia)
                    .addComponent(txt_aCongruencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_bCongruencia)
                    .addComponent(txt_bCongruencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_esCongruencia))
                .addGap(18, 18, 18)
                .addComponent(btn_calcularCongruencia)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_infoCongruencia)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ayudaCongruencia)
                            .addComponent(btn_limpiarCongruencia)
                            .addComponent(btn_regresarCongruencia))
                        .addGap(35, 35, 35))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCongruencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCongruencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCongruencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCongruencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCongruencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ayudaCongruencia;
    private javax.swing.JButton btn_calcularCongruencia;
    private javax.swing.JButton btn_limpiarCongruencia;
    private javax.swing.JButton btn_regresarCongruencia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_aCongruencia;
    private javax.swing.JLabel lb_bCongruencia;
    private javax.swing.JLabel lb_esCongruencia;
    private javax.swing.JLabel lb_infoCongruencia;
    private javax.swing.JLabel lb_tituloCongruencia;
    private javax.swing.JTextField txt_aCongruencia;
    private javax.swing.JTextField txt_bCongruencia;
    private javax.swing.JTextArea txt_solucionCongruencia;
    // End of variables declaration//GEN-END:variables

    private void setFonts() {
        FontBSD fonts = new FontBSD();
        lb_tituloCongruencia.setFont(fonts.getMyFont(1, 48));
        lb_aCongruencia.setFont(fonts.getMyFont(1, 18));
        lb_bCongruencia.setFont(fonts.getMyFont(1, 18));
        lb_esCongruencia.setFont(fonts.getMyFont(1, 18));
        lb_infoCongruencia.setFont(fonts.getMyFont(1, 14));
        txt_aCongruencia.setFont(fonts.getMyFont(1, 18));
        txt_bCongruencia.setFont(fonts.getMyFont(1, 18));
        txt_solucionCongruencia.setFont(fonts.getMyFont(1, 18));
        btn_calcularCongruencia.setFont(fonts.getMyFont(1, 18));
        btn_regresarCongruencia.setFont(fonts.getMyFont(1, 18));
        btn_limpiarCongruencia.setFont(fonts.getMyFont(1, 18));
        btn_ayudaCongruencia.setFont(fonts.getMyFont(1, 18));
    }
}
