/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.ControladorVistaModuloInverso;
import Recursos.fuentes.FontBSD;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author ALEX
 */
public class VistaModuloInverso extends javax.swing.JFrame {
    private ControladorVistaModuloInverso manejador = new ControladorVistaModuloInverso(this);

    /**
     * Creates new form VistaAlgoritmo
     */
    public VistaModuloInverso() {
        initComponents();
        //Centramos la ventana
        this.setLocationRelativeTo(null);
        //Garantizamos la fuente y el estilo de la interfaz
        setFont();
        //Agregamos el manejador a cada uno de los botones de la interfaz
        btn_ayudaModuloInverso.addActionListener(manejador);
        btn_calcularModuloInverso.addActionListener(manejador);
        btn_limpiarModuloInverso.addActionListener(manejador);
        btn_regresarModuloInverso.addActionListener(manejador);
        //hacemos clic en el boton de limpiar
        btn_limpiarModuloInverso.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_tituloModuloInverso = new javax.swing.JLabel();
        lb_inversoModuloInverso = new javax.swing.JLabel();
        txt_aModuloInverso = new javax.swing.JTextField();
        lb_moduloModuloInverso = new javax.swing.JLabel();
        txt_bModuloInverso = new javax.swing.JTextField();
        lb_esModuloInverso = new javax.swing.JLabel();
        btn_calcularModuloInverso = new javax.swing.JButton();
        txt_resultadoModuloInverso = new javax.swing.JTextField();
        btn_regresarModuloInverso = new javax.swing.JButton();
        btn_limpiarModuloInverso = new javax.swing.JButton();
        btn_ayudaModuloInverso = new javax.swing.JButton();
        lb_infoModuloInverso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));

        lb_tituloModuloInverso.setFont(new java.awt.Font("BSD I Believe In Love", 1, 48)); // NOI18N
        lb_tituloModuloInverso.setForeground(new java.awt.Color(240, 240, 240));
        lb_tituloModuloInverso.setText("Modulo Inverso");

        lb_inversoModuloInverso.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        lb_inversoModuloInverso.setForeground(new java.awt.Color(240, 240, 240));
        lb_inversoModuloInverso.setText("El inverso de:  ");

        txt_aModuloInverso.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        txt_aModuloInverso.setText("XXX");

        lb_moduloModuloInverso.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        lb_moduloModuloInverso.setForeground(new java.awt.Color(240, 240, 240));
        lb_moduloModuloInverso.setText("modulo:  ");

        txt_bModuloInverso.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        txt_bModuloInverso.setText("XXX");

        lb_esModuloInverso.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        lb_esModuloInverso.setForeground(new java.awt.Color(240, 240, 240));
        lb_esModuloInverso.setText("es:   ");

        btn_calcularModuloInverso.setBackground(new java.awt.Color(243, 156, 18));
        btn_calcularModuloInverso.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        btn_calcularModuloInverso.setForeground(new java.awt.Color(240, 240, 240));
        btn_calcularModuloInverso.setText("calcular");

        txt_resultadoModuloInverso.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        txt_resultadoModuloInverso.setText("XXX");

        btn_regresarModuloInverso.setBackground(new java.awt.Color(243, 156, 18));
        btn_regresarModuloInverso.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        btn_regresarModuloInverso.setForeground(new java.awt.Color(240, 240, 240));
        btn_regresarModuloInverso.setText("regresar");

        btn_limpiarModuloInverso.setBackground(new java.awt.Color(243, 156, 18));
        btn_limpiarModuloInverso.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        btn_limpiarModuloInverso.setForeground(new java.awt.Color(240, 240, 240));
        btn_limpiarModuloInverso.setText("limpiar campos");

        btn_ayudaModuloInverso.setBackground(new java.awt.Color(243, 156, 18));
        btn_ayudaModuloInverso.setFont(new java.awt.Font("BSD I Believe In Love", 1, 18)); // NOI18N
        btn_ayudaModuloInverso.setForeground(new java.awt.Color(240, 240, 240));
        btn_ayudaModuloInverso.setText("ayuda");

        lb_infoModuloInverso.setFont(new java.awt.Font("BSD I Believe In Love", 1, 14)); // NOI18N
        lb_infoModuloInverso.setForeground(new java.awt.Color(240, 240, 240));
        lb_infoModuloInverso.setText("Info:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_infoModuloInverso))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(btn_calcularModuloInverso)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_tituloModuloInverso)
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_regresarModuloInverso)
                        .addGap(18, 18, 18)
                        .addComponent(btn_limpiarModuloInverso)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ayudaModuloInverso)
                        .addGap(44, 44, 44))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(lb_inversoModuloInverso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_aModuloInverso, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_moduloModuloInverso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_bModuloInverso, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_esModuloInverso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_resultadoModuloInverso, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 139, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_tituloModuloInverso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_inversoModuloInverso)
                    .addComponent(txt_aModuloInverso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_moduloModuloInverso)
                    .addComponent(txt_bModuloInverso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_esModuloInverso)
                    .addComponent(txt_resultadoModuloInverso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btn_calcularModuloInverso)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ayudaModuloInverso)
                    .addComponent(btn_limpiarModuloInverso)
                    .addComponent(btn_regresarModuloInverso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_infoModuloInverso)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaModuloInverso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaModuloInverso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaModuloInverso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaModuloInverso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaModuloInverso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ayudaModuloInverso;
    private javax.swing.JButton btn_calcularModuloInverso;
    private javax.swing.JButton btn_limpiarModuloInverso;
    private javax.swing.JButton btn_regresarModuloInverso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_esModuloInverso;
    private javax.swing.JLabel lb_infoModuloInverso;
    private javax.swing.JLabel lb_inversoModuloInverso;
    private javax.swing.JLabel lb_moduloModuloInverso;
    private javax.swing.JLabel lb_tituloModuloInverso;
    private javax.swing.JTextField txt_aModuloInverso;
    private javax.swing.JTextField txt_bModuloInverso;
    private javax.swing.JTextField txt_resultadoModuloInverso;
    // End of variables declaration//GEN-END:variables
    /**
     * Metodo que garantiza el estilo y tipo de fuente de la interfaz, independientemente 
     * del sistema operativo
     */
    private void setFont() {
        FontBSD fonts = new FontBSD();
        lb_tituloModuloInverso.setFont(fonts.getMyFont(1, 48));
        lb_esModuloInverso.setFont(fonts.getMyFont(1, 18));
        lb_infoModuloInverso.setFont(fonts.getMyFont(1, 14));
        lb_inversoModuloInverso.setFont(fonts.getMyFont(1, 18));
        lb_moduloModuloInverso.setFont(fonts.getMyFont(1, 18));
        btn_ayudaModuloInverso.setFont(fonts.getMyFont(1, 18));
        btn_calcularModuloInverso.setFont(fonts.getMyFont(1, 18));
        btn_limpiarModuloInverso.setFont(fonts.getMyFont(1, 18));
        btn_regresarModuloInverso.setFont(fonts.getMyFont(1, 18));
    }

    public JLabel getLb_infoModuloInverso() {
        return lb_infoModuloInverso;
    }

    public JTextField getTxt_aModuloInverso() {
        return txt_aModuloInverso;
    }

    public JTextField getTxt_bModuloInverso() {
        return txt_bModuloInverso;
    }

    public JTextField getTxt_resultadoModuloInverso() {
        return txt_resultadoModuloInverso;
    }
    
    
}
